# Generated by Django 3.0.3 on 2020-06-01 17:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50, verbose_name='Название мероприятия')),
                ('event_text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст записи')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
