# Generated by Django 3.0.3 on 2020-07-04 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название стьатьи')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст записи')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('date_a', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название блока')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание блока')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инфорамация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
